CREATE VIEW CITY_VIEW AS
SELECT NAME_DESC, STARS FROM BUSINESS WHERE CITY = 'Mesa';

SELECT NAME_DESC FROM BUSINESS WHERE REVIEW_COUNT > 60 AND STARS = 1;

SELECT CITY, STATE, COUNT(*) FROM BUSINESS WHERE STARS = 1 GROUP BY CITY, STATE;

SELECT NAME_DESC, AVG(STARS) FROM BUSINESS WHERE NAME_DESC = 'Taco Bell' GROUP BY NAME_DESC;


SELECT COUNT(*) FROM BUSINESS;

CREATE VIEW BUSINESS_REVIEWS_VIEW AS SELECT b.BUSINESS_ID, b.NAME_DESC as NAME, AVG(r.STARS) as AVERAGE_RATING, COUNT(*) as REVIEW_COUNT FROM REVIEWS r JOIN BUSINESS b ON r.BUSINESS_ID = b.BUSINESS_ID GROUP BY b.BUSINESS_ID, b.NAME_DESC;
DROP VIEW BUSINESS_REVIEWS_VIEW;

SELECT NAME 
